CREATE TABLE IF NOT EXISTS `wp_payment_set` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`wxmchid`  varchar(2000) NOT NULL  COMMENT 'Mchid',
`quick_merid`  varchar(255) NOT NULL  COMMENT '银联在线merid',
`wappartnerid`  varchar(255) NOT NULL  COMMENT '财付通标识WAP',
`partnerkey`  varchar(255) NOT NULL  COMMENT '财付通Key',
`partnerid`  varchar(255) NOT NULL  COMMENT '财付通标识',
`key`  varchar(255) NOT NULL  COMMENT 'KEY',
`pid`  varchar(255) NOT NULL  COMMENT 'PID',
`zfbname`  varchar(255) NOT NULL  COMMENT '帐号',
`wxappsecret`  varchar(255) NOT NULL  COMMENT 'AppSecret',
`wxpaysignkey`  varchar(255) NOT NULL  COMMENT '密钥Key',
`quick_merabbr`  varchar(255) NOT NULL  COMMENT '商户名称',
`quick_security_key`  varchar(255) NOT NULL  COMMENT '银联在线Key',
`wxpartnerid`  varchar(255) NOT NULL  COMMENT '微信partnerid',
`wxpartnerkey`  varchar(255) NOT NULL  COMMENT '微信partnerkey',
`wappartnerkey`  varchar(255) NOT NULL  COMMENT 'WAP财付通Key',
`wxappid`  varchar(255) NOT NULL  COMMENT 'appid',
`ctime`  int(10) NOT NULL  COMMENT '创建时间',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`wxv3key`  varchar(2000) NOT NULL  COMMENT 'Key',
`wxv3appsecret`  varchar(2000) NOT NULL  COMMENT 'Appsecret',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('payment_set','支付配置','0','','1','{"1":["quick_merabbr","quick_merid","wappartnerid","wxappid","partnerid","partnerkey","zfbname","pid","key","wxappsecret","wxpaysignkey","quick_security_key","wxpartnerid","wxpartnerkey","wappartnerkey","wxmchid","wxv3key","wxv3appsecret"]}','1:基础','','','','','','10','','','1406958084','1426312079','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxmchid','Mchid','varchar(2000) NOT NULL','string','','商户号','1','','0','1','1','1426312129','1426310763','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('quick_merid','银联在线merid','varchar(255) NOT NULL','string','','','1','','0','0','1','1407066572','1407066572','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wappartnerid','财付通标识WAP','varchar(255) NOT NULL','string','','财付通商户身份的标识(WAP)','1','','0','0','1','1406958662','1406958662','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('partnerkey','财付通Key','varchar(255) NOT NULL','string','','财付通商户权限密钥Key','1','','0','0','1','1406958522','1406958522','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('partnerid','财付通标识','varchar(255) NOT NULL','string','','财付通商户身份的标识','1','','0','0','1','1406958499','1406958499','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('key','KEY','varchar(255) NOT NULL','string','','','1','','0','0','1','1406958379','1406958379','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pid','PID','varchar(255) NOT NULL','string','','','1','','0','0','1','1406958364','1406958364','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('zfbname','帐号','varchar(255) NOT NULL','string','','支付宝账号','1','','0','0','1','1406958350','1406958350','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxappsecret','AppSecret','varchar(255) NOT NULL','string','','','1','','0','0','1','1406958311','1406958311','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxpaysignkey','密钥Key','varchar(255) NOT NULL','string','','公众号支付请求中用于加密的密钥Key','1','','0','0','1','1406958270','1406958270','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('quick_merabbr','商户名称','varchar(255) NOT NULL','string','','','1','','0','0','1','1407066591','1407066591','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('quick_security_key','银联在线Key','varchar(255) NOT NULL','string','','','1','','0','0','1','1407066551','1407066551','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxpartnerid','微信partnerid','varchar(255) NOT NULL','string','','','1','','0','0','1','1407049473','1407049473','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxpartnerkey','微信partnerkey','varchar(255) NOT NULL','string','','','1','','0','0','1','1407049405','1407049405','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wappartnerkey','WAP财付通Key','varchar(255) NOT NULL','string','','财付通商户权限密钥Key(WAP)','1','','0','0','1','1406958701','1406958701','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxappid','appid','varchar(255) NOT NULL','string','','微信公众号唯一标识','1','','0','1','1','1426312165','1406958232','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','创建时间','int(10) NOT NULL','datetime','','','0','','0','0','1','1406958137','1406958137','','3','','regex','time','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','0','','0','0','1','1406958112','1406958112','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxv3key','Key','varchar(2000) NOT NULL','string','','商户支付密钥Key','1','','0','1','1','1426310804','1426310804','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxv3appsecret','Appsecret','varchar(2000) NOT NULL','string','','JSAPI接口中获取openid','1','','0','1','1','1426310866','1426310866','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;